language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
    - pylint cortex --errors-only
script:
    - coverage run --source='cortex/core' manage.py test
    - coverage report --fail-under=75

