language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
addons:
    postgres: "9.3"
install: "pip install -r requirements.txt"
before_script:
    - pylint cortex --errors-only
    - psql -c 'create database cortex_test;' -U postgres
script:
    - coverage run --source='cortex/core' manage.py test
    - coverage report --fail-under=75

